name: zetrix_vc_flutter
description: Zetrix flutter SDK for Verifiable Credential (Verifiable Presentation)
version: 0.0.4
homepage: https://docs.zetrix.com/en
repository: https://github.com/Zetrix-Chain/zetrix-vc-flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  pinenacl: ^0.6.0
  bs58: ^1.0.2
  cryptography: ^2.7.0
  hex: ^0.2.0
  pointycastle: ^4.0.0
  convert: ^3.1.2
  ffi: ^2.1.4
  flutter_rust_bridge: ^2.10.0
  collection: ^1.18.0
  path: ^1.9.1
  archive: ^4.0.7
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

flutter:
  plugin:
    platforms:
      android:
        package: com.zetrix.bbs
        pluginClass: BbsFlutterPlugin
      ios:
        pluginClass: BbsFlutterPlugin
